// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spec.proto

package pubsub

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	v1 "google.golang.org/genproto/googleapis/pubsub/v1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ReceivedMessage and its corresponding acknowledgment ID.
type ReceivedMessage struct {
	// This ID can be used to acknowledge the received message.
	AckId string `protobuf:"bytes,1,opt,name=ack_id,json=ackId,proto3" json:"ack_id,omitempty"`
	// The message.
	Message *v1.PubsubMessage `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Delivery attempt counter is 1 + (the sum of number of NACKs and number of
	// ack_deadline exceeds) for this message.
	//
	// A NACK is any call to ModifyAckDeadline with a 0 deadline. An ack_deadline
	// exceeds event is whenever a message is not acknowledged within
	// ack_deadline. Note that ack_deadline is initially
	// Subscription.ackDeadlineSeconds, but may get extended automatically by
	// the client library.
	//
	// The first delivery of a given message will have this value as 1. The value
	// is calculated at best effort and is approximate.
	//
	// If a DeadLetterPolicy is not set on the subscription, this will be 0.
	// <b>EXPERIMENTAL:</b> This feature is part of a closed alpha release. This
	// API might be changed in backward-incompatible ways and is not recommended
	// for production use. It is not subject to any SLA or deprecation policy.
	DeliveryAttempt int32 `protobuf:"varint,3,opt,name=delivery_attempt,json=deliveryAttempt,proto3" json:"delivery_attempt,omitempty"`
	// Required. The name of the subscription.
	// Format is `projects/{project}/subscriptions/{sub}`.
	Subscription         string   `protobuf:"bytes,4,opt,name=subscription,proto3" json:"subscription,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceivedMessage) Reset()         { *m = ReceivedMessage{} }
func (m *ReceivedMessage) String() string { return proto.CompactTextString(m) }
func (*ReceivedMessage) ProtoMessage()    {}
func (*ReceivedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_423806180556987f, []int{0}
}

func (m *ReceivedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceivedMessage.Unmarshal(m, b)
}
func (m *ReceivedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceivedMessage.Marshal(b, m, deterministic)
}
func (m *ReceivedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceivedMessage.Merge(m, src)
}
func (m *ReceivedMessage) XXX_Size() int {
	return xxx_messageInfo_ReceivedMessage.Size(m)
}
func (m *ReceivedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceivedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ReceivedMessage proto.InternalMessageInfo

func (m *ReceivedMessage) GetAckId() string {
	if m != nil {
		return m.AckId
	}
	return ""
}

func (m *ReceivedMessage) GetMessage() *v1.PubsubMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ReceivedMessage) GetDeliveryAttempt() int32 {
	if m != nil {
		return m.DeliveryAttempt
	}
	return 0
}

func (m *ReceivedMessage) GetSubscription() string {
	if m != nil {
		return m.Subscription
	}
	return ""
}

func init() {
	proto.RegisterType((*ReceivedMessage)(nil), "phogolabs.cloud.pubsub.ReceivedMessage")
}

func init() { proto.RegisterFile("spec.proto", fileDescriptor_423806180556987f) }

var fileDescriptor_423806180556987f = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x89, 0xba, 0x2b, 0x46, 0x61, 0x25, 0xa0, 0x14, 0x41, 0x2c, 0x7b, 0xaa, 0x1e, 0x52,
	0x56, 0x4f, 0xe2, 0x49, 0x6f, 0x1e, 0x04, 0xe9, 0xd1, 0xcb, 0x92, 0x3f, 0x43, 0x36, 0x6c, 0xeb,
	0x84, 0x26, 0x29, 0xf8, 0xb5, 0xfc, 0x84, 0x42, 0x92, 0x0a, 0x7b, 0xca, 0xcb, 0xe3, 0xcd, 0x9b,
	0xf9, 0x51, 0xea, 0x1d, 0x28, 0xee, 0x46, 0x0c, 0xc8, 0xae, 0xdd, 0x0e, 0x0d, 0xf6, 0x42, 0x7a,
	0xae, 0x7a, 0x8c, 0x9a, 0xbb, 0x28, 0x7d, 0x94, 0x37, 0xb7, 0x06, 0xd1, 0xf4, 0xd0, 0xe6, 0x6f,
	0x3b, 0x6d, 0x8a, 0xca, 0x63, 0xeb, 0x5f, 0x42, 0x57, 0x1d, 0x28, 0xb0, 0x13, 0xe8, 0x0f, 0xf0,
	0x5e, 0x18, 0x60, 0x57, 0x74, 0x29, 0xd4, 0x7e, 0x6b, 0x75, 0x45, 0x6a, 0xd2, 0x9c, 0x75, 0x0b,
	0xa1, 0xf6, 0xef, 0x9a, 0x3d, 0xd3, 0xd3, 0x21, 0x27, 0xaa, 0xa3, 0x9a, 0x34, 0xe7, 0x8f, 0x77,
	0x3c, 0x77, 0x97, 0x55, 0x7c, 0xda, 0xf0, 0xcf, 0xa4, 0x4a, 0x51, 0x37, 0xe7, 0xd9, 0x3d, 0xbd,
	0xd4, 0xd0, 0xdb, 0x09, 0xc6, 0x9f, 0xad, 0x08, 0x01, 0x06, 0x17, 0xaa, 0xe3, 0x9a, 0x34, 0x8b,
	0x6e, 0x35, 0xfb, 0xaf, 0xd9, 0x66, 0x6b, 0x7a, 0xe1, 0xa3, 0xf4, 0x6a, 0xb4, 0x2e, 0x58, 0xfc,
	0xae, 0x4e, 0xd2, 0x09, 0x07, 0xde, 0xdb, 0xc3, 0x57, 0x63, 0x6c, 0xd8, 0x45, 0xc9, 0x15, 0x0e,
	0xed, 0x3f, 0x78, 0x9b, 0xc0, 0x0b, 0xdf, 0x4b, 0x7e, 0xe4, 0x32, 0x71, 0x3e, 0xfd, 0x05, 0x00,
	0x00, 0xff, 0xff, 0x14, 0x51, 0x3d, 0x59, 0x2c, 0x01, 0x00, 0x00,
}
